### ISSUE TITLE
Unintialised int_vector in XG when calling default constructor

### ISSUE THREAD

**Issue by cartoonist** [vgteam/vg#1641]
I am using `libvg` version 1.6.0 and trying to re-use `XG` class. I am extending the XG functionalities by deriving yet another class from `XG`:

```c++
class YaXG : public xg::XG {
    using xg::XG::XG;
};
```

I expect that I can instantiate the `YaXG` class using default constructor and call the `load` function later:

```c++
YaXG graph;
graph.load( in );
```

But the above example gets aborted by segmentation fault signal and complaining about an invalid pointer:

```
Segmentation fault
*** Error in `/home/ghaffari/workspace/cgrem/bin/debug/grem': realloc(): invalid pointer: 0x00007fffffff9970 ***
```

Surprisingly, calling directly the constructor which gets the input stream works:

```
YaXG graph( in );
```

and of course, using the `XG` also works fine:

```
XG graph;
graph.load( in );
```

But in my case, I need to use the new class derived from `XG` and also the input stream is not known at the time of definition.

Further debuging by gdb, showed that the problem is the uninitialised `XG::i_iv` member variable ([xg.cpp:173](https://github.com/vgteam/vg/blob/1f8d1fa24521243546fa12d060b1876cfbf692ab/src/xg.cpp#L173)):
```
(gdb) p i_iv
$1 = {m_size = 3735, m_data = 0x7fffffff9970, m_width = 9 '\t', raw = {vec = @0x555555bb2215}}
```
where `m_size` should be zero.

This is a weird behaviour. Do you have any idea, why the default constructor calling by derived class doesn't initialise the `int_vector`s or particularly `i_iv`? Shouldn't `XG` initialise all member variable by calling default constructor since they are private to the derived classes?

**Comment by ekg** [comment]
In v1.7.0 this should be resolved as there is no i_iv vector.

**Comment by cartoonist** [comment]
Using 1392b1beeeb577becf51e16a682aae3b00baa722 and it did not resolved the issue.
